### ISSUE TITLE
How to add a csv or geojson source?

### ISSUE THREAD

**Issue by kosvrouvas** [brendan-ward/gatsby-starter-mapbox#1]
Hi, excellent work, how to add a csv or geojson source?

**Comment by brendan-ward** [comment]
@kosvrouvas GeoJSON is supported directly by Mapbox GL JS.

You can pass in an array of `layers` to the `Map` component, which get added into the map at the time the map is constructed.

You can add your GeoJSON directly as a source within a layer like so:
```
layers = [
  {
    id: '1',
    source: {
      type: 'geojson',
      data: {
        type: 'Polygon',
        coordinates: [
          [
            [-124.03564453125, 46.195042108660154],
            [-124.5849609375, 42.89206418807337],
            [-124.365234375, 42.049292638686836],
            [-117.00439453125, 42.049292638686836],
            [-116.96044921875, 45.99696161820381],
            [-118.98193359375, 46.027481852486645],
            [-121.201171875, 45.66012730272194],
            [-122.32177734375, 45.61403741135093],
            [-122.76123046875, 45.644768217751924],
            [-122.98095703125, 46.195042108660154],
            [-123.6181640625, 46.240651955001695],
            [-124.03564453125, 46.195042108660154],
          ],
        ],
      },
    },
    type: 'fill',
    paint: {
      'fill-color': 'red',
      'fill-opacity': 0.5,
    },
  },
]
```

Or you can add it as a [`source`](https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#geojson) and then add one or more layers that use it.  To do this, you would need to pass both `sources` and `layers` to the `Map` component.

[Example](https://github.com/brendan-ward/gatsby-starter-mapbox/blob/master/src/pages/map-geojson.jsx)



CSV data need to be transformed to GeoJSON before it can be added to the map.  [Example](https://bl.ocks.org/danswick/effa94375f9ed24cea9f).

Note: there isn't anything in place now that handles adding layers or data after the map component is constructed.  For example, when you are fetching those data from a remote resource.  You would need to adapt the `Map` component to mee that need, adding in appropriate hooks to support adding data after creation.  It is entirely possible, but more complex than I wanted to introduce here.

If your data are small and static, you can "bake" them into your Gatsby application, and use Gatsby's GraphQL API to make those data available to the `Map` component.


A very complex [example](https://github.com/consbio/batamp-viz):
I have location data stored within a custom JSON structure "baked" in to my Gatsby application; `detectors` have lat / long coordinates.

In a page, I then consume those data via Gatsby's GraphQL API (for a given bat species): https://github.com/consbio/batamp-viz/blob/master/ui/src/templates/Species.jsx

Then in my `Map` [component](https://github.com/consbio/batamp-viz/blob/master/ui/src/components/Map/index.jsx), I convert those to a GeoJSON source, and have various functions and hooks to handle updating those when the user changes their view into the data.  

[See it in action](https://visualize.batamp.databasin.org/species/mylu)
