### ISSUE TITLE
add DropDownLayerChooser 

### ISSUE THREAD

**Issue by smnorris** [brendan-ward/gatsby-starter-mapbox#5]
It would be nice to include a layer control in this starter. I miss leaflet's simple layer control in mapbox-gl.js... but this starter seems like a good alternative.
https://github.com/astutespruce/sarp-connectivity/blob/master/ui/src/components/Map/DropDownLayerChooser.jsx

I'll see if I can figure it out and create a PR but any guidance is appreciated.
Thanks for publishing the Barrier Prioritization Tool - so much good stuff.

**Comment by brendan-ward** [comment]
@smnorris Adding a layer chooser seems beyond the intent of the starter; I want to keep this very lean.  I would recommend developing that as a component you add in after starting from this starter.  Happy to link to your usage as an example of doing that.

Changing layers is much more complex in Mapbox GL than in Leaflet...

I don't know if you saw it, but I had stubbed out a basemap style chooser in this component: https://github.com/brendan-ward/gatsby-starter-mapbox/blob/master/src/components/Map/StyleSelector.jsx

Just in case it helps think through managing the state of the map style as you add / remove layers.

**Comment by smnorris** [comment]
Thanks @brendan-ward, that make sense. My strategy for now is to use XYZ raster tile backgrounds and just a few toggleable MVT layers on top, much like the basic leaflet geojson examples.  I think that should avoid much of the additional complexity of managing layers in GL. Thanks for that link, I didn't realize you were switching between vector tile basemaps.

**Comment by astridx** [comment]
> @brendan-ward Happy to link to your usage as an example of doing that.

I would be happy if you like my usage and you would link it as an example.
[Code](https://github.com/astridx/gatsby-starter-mapbox-examples)
[Demo](https://astridx.github.io/gatsbystarter/gatsby-starter-mapbox-examples/map-show-and-hide-layers)

**Comment by brendan-ward** [comment]
@astridx added a cross-link, thanks!  These look like nice examples of adding additional components on top of this starter.
